#include <alef.h>

/*
 *  announce a network service.
 */
int
announce(byte *, byte *)
{
	werrstr("not implemented");
	return - 1;
}


/*
 *  accept a call, return an fd to the open data file
 */
int
accept(int, byte *)
{
	werrstr("not implemented");
	return - 1;
}


/*
 *  reject a call, tell device the reason for the rejection
 */
int
reject(int, byte *, byte *)
{
	werrstr("not implemented");
	return - 1;
}


